from . import barmex_customer_codes
from . import barmex_customer_product_pricelist
from . import barmex_dialog_box
from . import barmex_dialog_box_line
from . import barmex_product_brand
from . import barmex_product_group
from . import barmex_product_pricelist
from . import barmex_product_product
from . import barmex_product_speciallity
from . import barmex_product_subgroup
from . import barmex_product_subline
from . import barmex_product_template
from . import barmex_petition_relation
