from . import barmex_addenda
from . import barmex_addenda_record
from . import barmex_classification
from . import barmex_collector
from . import barmex_corporate
from . import barmex_partner_type
from . import barmex_vendor_price
from . import barmex_product_classification
from . import barmex_product_classification_process
from . import barmex_invoice
from . import barmex_shipping
from . import barmex_reason
from . import barmex_sale_zone
from . import barmex_res_partner
