{
    'name': 'OS Barmex Sale & Purchase',
    'version': '15.0',
    'author': 'OS Barmex Sale & Purchase',
    'website': '',
    'category': 'sale',
    'sequence': 5,
    'licence': 'AGPL-3',
    'summary': 'OS Barmex Sale & Purchase',
    'depends': [
        'os_barmex',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/barmex_crm_lead.xml',
        'views/barmex_partner_type.xml',
        'views/barmex_purchase_order.xml',
        'views/barmex_reason.xml',
        'views/barmex_res_config_settings.xml',
        'views/barmex_res_partner.xml',
        'views/barmex_res_partner_custom.xml',
        'views/barmex_res_user.xml',
        'views/barmex_sale_order.xml',
        'views/barmex_sale_zone.xml',
        'views/barmex_server_action.xml',
        'views/barmex_vendor_type.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
