{
    'name': 'OS Barmex',
    'version': '15.0',
    'author': 'OS Barmex',
    'website': '',
    'category': 'hr',
    'sequence': 1,
    'licence': 'AGPL-3',
    'summary': 'OS Barmex',
    'depends': [
        'base',
        'account',
        'account_accountant',
        'account_reports',
        'contacts',
        'crm',
        'hr',
        'website',
        'hr_expense',
        'l10n_mx_edi',
        'l10n_mx',
        'mail',
        'product',
        'purchase',
        'stock',
        'sale',
        'sale_management',
        'uom',
        'account_debit_note',
        'product_unspsc'
    ],
    'data': [
        'security/barmex_res_partner.xml',
        'security/barmex_account_security.xml',
        'security/barmex_model_security.xml',
        'security/ir.model.access.csv',
        'data/company_filters.xml',
        'data/barmex_reason.xml',


        'views/barmex_addenda.xml',
        'views/barmex_classification.xml',
        'views/barmex_product_classification.xml',
        'views/barmex_product_classification_process.xml',
        'views/barmex_corporate.xml',
        'views/barmex_invoice.xml',
        'views/barmex_partner_type.xml',
        'views/barmex_reason.xml',
        'views/barmex_sale_zone.xml',
        'views/menu.xml',

        'templates/website_homepage1.xml',
        'templates/calsonickansei.xml',
        'templates/del_valle.xml',
        'templates/envases.xml',
        'templates/femsa.xml',
        'templates/hornos.xml',
        'templates/lala.xml',
        'templates/mabe.xml',
        'templates/minera.xml',
        'templates/pemex.xml',
        'templates/pilgrims.xml',
        'templates/porcelanite.xml',
        'templates/sabritas.xml',
        'templates/sanmina.xml',
        'templates/sergoba.xml',
        'templates/zf.xml'
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
