from . import barmex_crm_lead
from . import barmex_crm_team
from . import barmex_purchase_order
from . import barmex_purchase_order_line
from . import barmex_res_company
from . import barmex_res_config_settings
from . import barmex_res_partner_bank
from . import barmex_res_user
from . import barmex_sale_order
from . import barmex_sale_order_line
from . import barmex_vendor_type
from . import res_partner
